version: '3.8'

services:
  app:
    build: .
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8000 --timeout 60
    expose:
      - 8000
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:1.18.0
    ports:
      - 80:80
      # Uncomment below for SSL
      # - 443:443
    volumes:
      - ./frontend:/frontend/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL certs
      # - ./cert.pem:/etc/nginx/cert.pem:ro
      # - ./key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - app
